deploy_edition5

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -9,7 +9,6 @@ env:
   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_KEY }}
   IMAGE_NAME: taskmap_repo
-  TAG: latest
 
 jobs:
   build-and-push-backend:
@@ -41,6 +40,7 @@ jobs:
         run: |
           docker build -t $DOCKERHUB_USERNAME/qr-sigh_frontend ./frontend
           docker push $DOCKERHUB_USERNAME/qr-sigh_frontend
+  
   deploy:
     needs:
       - build-and-push-backend
@@ -52,6 +52,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
       
+      - name: Check if file exists
+        run: |
+          if [[ ! -f docker-compose.production.yaml ]]; then
+            echo "Error: File docker-compose.production.yaml not found."
+            exit 1
+          fi
+
       - name: Copy docker-compose.yml via ssh
         uses: appleboy/scp-action@master
         with:
@@ -60,7 +67,7 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           passphrase: ${{ secrets.SSH_PASSPHRASE }}
           source: "docker-compose.production.yaml"
-          target: "~/taskmap"
+          target: "/root/taskmap"
       
       - name: Execute commands on remote server
         uses: appleboy/ssh-action@master
